# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BUILD_SOURCE_DIRS "/Users/kevin/git/cpp/EscapeTheFate;/Users/kevin/git/cpp/EscapeTheFate/build-android")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/Users/kevin/Library/Android/sdk/cmake/3.31.6/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "Escape The Fate built using CMake")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/Users/kevin/git/cpp/EscapeTheFate;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_CONTACT "kevin@supergoon.com")
set(CPACK_NSIS_DISPLAY_NAME "Escape the Fate")
set(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
set(CPACK_NSIS_HELP_LINK "https://supergoon.com")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_MUI_ICON "/Users/kevin/git/cpp/EscapeTheFate/cmake/AppIcon.ico")
set(CPACK_NSIS_MUI_UNIICON "/Users/kevin/git/cpp/EscapeTheFate/cmake/AppIcon.ico")
set(CPACK_NSIS_PACKAGE_NAME "Escape the Fate")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_NSIS_URL_INFO_ABOUT "https://escapethefate-dev.supergoon.com")
set(CPACK_OBJCOPY_EXECUTABLE "/Users/kevin/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/Users/kevin/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/Users/kevin/git/cpp/EscapeTheFate/build-android/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/Users/kevin/git/cpp/EscapeTheFate/README.md")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "2D deckbuilding JRPG")
set(CPACK_PACKAGE_DIRECTORY "/Users/kevin/git/cpp/EscapeTheFate/build-android/packages")
set(CPACK_PACKAGE_EXECUTABLES "EscapeTheFate;Escape the Fate")
set(CPACK_PACKAGE_FILE_NAME "EscapeTheFate-0.1.0-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "EscapeTheFate 0.1.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "EscapeTheFate 0.1.0")
set(CPACK_PACKAGE_NAME "EscapeTheFate")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Supergoon Games")
set(CPACK_PACKAGE_VERSION "0.1.0")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_READELF_EXECUTABLE "/Users/kevin/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/Users/kevin/git/cpp/EscapeTheFate/LICENSE")
set(CPACK_RESOURCE_FILE_README "/Users/kevin/Library/Android/sdk/cmake/3.31.6/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/Users/kevin/Library/Android/sdk/cmake/3.31.6/share/cmake-3.31/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/Users/kevin/git/cpp/EscapeTheFate;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/kevin/git/cpp/EscapeTheFate/build-android/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "EscapeTheFate-0.1.0-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Android-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Android")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Android-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/kevin/git/cpp/EscapeTheFate/build-android/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
